services:
  postgres:
    container_name: postgres
    image: postgres:16.6
    restart: always
    shm_size: 256mb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_database.sql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: cs348
      POSTGRES_USER: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - cs348

  pgadmin:
      image: dpage/pgadmin4
      environment:
          PGADMIN_DEFAULT_EMAIL: 'placeholder@email.com'
          PGADMIN_DEFAULT_PASSWORD: 'cs348'
      ports:
          - 5433:80
      volumes:
          - ./pgadmin.json:/pgadmin4/servers.json
      networks:
          - cs348

networks:
  cs348:
    driver: bridge